version: "3"

services:
  web:
    build: .
    container_name: django
    volumes:
      - ./src:/app
      - static_volume:/app/staticfiles
    environment:
      DATABASE_URL: postgres://some_user:123@db/some_database
    restart: always
    command: gunicorn -c gunicorn.py SHRTN_engine.wsgi
    depends_on:
    - db
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5555:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    environment:
       POSTGRES_USER: some_user
       POSTGRES_PASSWORD: 123
       POSTGRES_DB: some_database
       PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    ports:
      - 8000:8989
    restart: always
    depends_on:
      - web
volumes:
  static_volume:
  pg_data:
